- _includes/import-scripts.html
- _includes/sgds-head.html
- package-lock.json
- Added google analytics
- Changed WOGAA script to header file instead
> Add analytics to SGDS website

- _includes/sgds-head.html
- Add hotjar analytics for heatmaps
> add hotjar analytics

- _includes/sgds-agencyhead.html
- Accidentally removed buttons in previous push
> re-add banner buttons on desktop version

- _includes/sgds-agencyhead.html
- _includes/sgds-head.html
- _layouts/layout-default.html
Add Google Tag Manager for event tracking, remove old event tracking code as it was not working
> Merge More Tracking Code

- Gemfile
- Gemfile.lock
- _config.yml
- _data/navigation.yml
- contents/docs/content-components.html
- contents/docs/content-templates.html
- contents/docs/index.html
- contents/learn/development/content-install-design-system.html
- contents/learn/development/index.html
- contents/learn/index.html
- contents/learn/writing/index.html
- index.html
- Split doc pages into component and template, this allows us to track users more accurately to find out which components are used the most
> Merge re-arrangement of pages

- _includes/sgds-footer.html
- components/_standard/footer.html
- sgds/sass/sgds-components/_sgds-footer.scss
update footer to only include 1 parent footer (instead of 2 separate doms)
> Update footer CSS and documentation for easier componentization

- components/_general/pagination.html
- sgds/sass/sgds-components/_sgds-pagination.scss
Edited pagination documentation.
added more css rules to handle ul and li within pagination
> Updated Pagination documentation, edit pagination classes

- components/_general/button.html
- sgds/sass/sgds-components/_sgds-button-secondary.scss
-Edit markup of button to use a button tag instead of link tag 
-alter secondary button css to hide default button styling
> Update button to use <button> instead of <a>

- components/_general/tooltip.html
> amended documentation for tooltip component in tooltip.html

- components/_general/progress-bar.html
> progress bar documentation write up

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Tackling #44, do let me know what you guys think.
> Added contribution.md and issue + pull requests templates

- collections/_general/accordion.html
- collections/_general/card.html
- collections/_general/notification.html
- collections/_helpers/colours.html
- collections/_layouts/container.html
- sgds/sass/sgds-base/_sgds-derived-variables.scss
- sgds/sass/sgds-customise/_sgds-initial-variables.scss
Adjust sgds colors to comply to WCAG AA level:
secondary: #3e69be
success: #008649
info: #17a2b8
link: #007bff
> Accessibility color

- _includes/sgds-agencyhead.html
- _includes/sgds-footer.html
- _includes/sgds-masthead.html
- _includes/visit-docs-section.html
- _layouts/layout-post.html
- _layouts/layout-sidenav.html
- _layouts/standard-template/layout-standard.html
- collections/_guides/index.html
- contents/docs/content-components.html
- contents/docs/content-templates.html
- index.html
- sgds/sass/sgds-layout/_sgds-container.scss
To fix left/right padding issues for sgds-container class for various breakpoints.
> Container fixes

- collections/_general/accordion.html
- collections/_general/breadcrumb.html
- collections/_general/button.html
- collections/_general/callout.html
- collections/_general/card.html
- collections/_general/dropdown.html
- collections/_general/hero.html
- collections/_general/iconography.html
- collections/_general/notification.html
- collections/_general/pagination.html
- collections/_general/tab.html
- collections/_general/table.html
- collections/_general/tag.html
- collections/_general/tooltip.html
- collections/_general/typography.html
- collections/_patterns/address.html
- collections/_patterns/date.html
- collections/_patterns/email-address.html
- collections/_patterns/names.html
- collections/_standard/footer.html
- collections/_standard/main-nav.html
- collections/_standard/masthead.html
- collections/_standard/side-nav.html
- contents/docs/getting-started.html
copy changes to docs/general, includes docs/standard
Ran locally
> Copy changes general

- collections/_standard/footer.html
- collections/_standard/main-nav.html
- collections/_standard/masthead.html
- collections/_standard/side-nav.html
- contents/docs/getting-started.html
Copy changes for /docs/standard
Ran locally
> Copy changes docs/standard

- README.md
- _config.yml
- package-lock.json
- package.json
- sgds/sass/sgds-customise/_sgds-initial-variables.scss
Update paragraph font size to 1.125rem;
>  Update paragraph font size to 1.125rem

- collections/_form/checkbox.html
- collections/_form/general-guidelines.html
- collections/_form/radio-buttons.html
- collections/_form/text-area.html
- collections/_form/text-input.html
- collections/_helpers/colours.html
- collections/_helpers/display.html
copy changes for /docs/form and /docs/helpers
Ran locally
> Copy changes form

- collections/_layout/container.html
- collections/_layout/grid.html
- collections/_layout/section.html
copy changes for /docs/layout, includes changes for /docs/form
Ran locally
> Copy changes layout

- collections/_form/radio-buttons.html
- collections/_form/text-input.html
- collections/_layout/grid.html
Made heading for Types and subsequent children smaller
Ran locally
> Edit headers

- collections/_form/checkbox.html
- collections/_form/general-guidelines.html
- collections/_form/radio-buttons.html
- collections/_form/text-area.html
- collections/_form/text-input.html
- collections/_helpers/colours.html
- collections/_helpers/display.html
- collections/_layout/container.html
- collections/_layout/grid.html
- collections/_layout/section.html
> Copy changes

- _data/icons.yml
- collections/_general/iconography.html
added missing icons to documentation
update aria labels to icons code snippets
> added missing icons to documentation, update aria labels to icons code snippets

- CHANGELOG.md
- collections/_form/checkbox.html
- collections/_form/text-area.html
- collections/_form/text-input.html
- collections/_general/iconography.html
- sgds/sass/sgds-base/_sgds-derived-variables.scss
- sgds/sass/sgds-components/_sgds-form.scss
- Added is-*color classes for hint text
- Removed .success & .error class for hint text
- Update input & text area documentation
> bug fixes for hint text classes

- _includes/guide-card-section.html
- _includes/visit-docs-section.html
- collections/_guides/designers-sketch-kit.html
- collections/_guides/developers-image-optimisation.html
- collections/_patterns/date.html
- contents/general/content-coming-soon.html
- contents/general/content-privacy.html
- contents/general/content-terms.html
- index.html
> Accessibility fixes for Header tag

- _includes/sgds-footer.html
- assets/custom-css/_content-typography.scss
- assets/custom-css/_sgds-example.scss
- assets/custom-css/_sgds-menu.scss
- collections/_general/iconography.html
- collections/_general/progress-bar.html
- collections/_general/step.html
> Convert code snippets into captures, remove icon entry in front matter

- CHANGELOG.md
- _includes/sgds-head.html
- _layouts/layout-sidenav.html
- apps/src/docs.js
- assets/custom-css/_grid.scss
- assets/custom-css/main.scss
- collections/_general/card.html
- collections/_general/datepicker.html
- collections/_general/file-upload.html
- collections/_general/hero.html
- collections/_general/iconography.html
- collections/_standard/side-nav.html
- contents/playground/index.html
- package-lock.json
- package.json
- sgds/js/index.js
- sgds/sass/sgds-base/_sgds-derived-variables.scss
- sgds/sass/sgds-base/_sgds-functions.scss
- sgds/sass/sgds-components/_all.scss
- sgds/sass/sgds-components/_sgds-card.scss
- sgds/sass/sgds-components/_sgds-file-upload.scss
- sgds/sass/sgds-components/_sgds-menu.scss
- sgds/sass/sgds-components/_sgds-step.scss
- sgds/sass/sgds-customise/_sgds-initial-variables.scss
- webpack.config.js
- [File upload](https://www.designsystem.gov.sg/docs/file-upload/)
- [Date picker](https://www.designsystem.gov.sg/docs/datepicker/)
- [Simple 2 level sidenav](https://www.designsystem.gov.sg/docs/side-nav/)
- [Highlight card](https://www.designsystem.gov.sg/docs/card/)
> Add new components

- CHANGELOG.md
- collections/_general/hero.html
- sgds/sass/sgds-components/_sgds-step.scss
> Fixed sgds step marker height and width properties. Remove hero banner container width 

- CHANGELOG.md
- _config.yml
- _data/navigation.yml
- _includes/component-list.html
- _includes/mobile-nav.html
- _includes/sidenav-templates.html
- _layouts/layout-full.html
- _layouts/layout-sidenav.html
- assets/custom-css/_grid.scss
- assets/custom-css/_sgds-example.scss
- collections/_default-templates/detail-page-with-sidenav.html
- collections/_default-templates/lading-page-with-banner.html
- collections/_default-templates/landing-page.html
- contents/templates/index.html
> add templates

- _includes/sgds-head.html
- css/sgds.css
- index.html
- sgds/sass/sgds-theme/_custom-variable.scss
- sgds/sass/sgds-theme/components/_dropdown.scss
- sgds/sass/sgds.scss
> added dropdown styling

- _includes/sgds-agencyhead.html
- _includes/sgds-masthead.html
- _layouts/layout-default.html
- assets/custom-css/_grid.scss
- assets/custom-css/_mobile-side-nav.scss
- assets/custom-css/_sgds-example.scss
- assets/custom-css/_sgds-syntax.scss
- assets/custom-css/main.scss
- collections/_standard/masthead.html
- sgds/js/index.js
- sgds/sass/sgds-components/_sgds-masthead.scss
> style(masthead): add masthead with toggle

- css/sgds.css
- index.html
- sgds/sass/sgds-theme/_sgds-variables.scss
- sgds/sass/sgds-theme/components/_all.scss
- sgds/sass/sgds-theme/components/_stepper.scss
- Added `is-completed,` `is-active` step example
- Convert to bootstrap variables.
- Update stepper colors to sgds-v2
> style(stepper): add stepper styling

- _includes/page-component/component-header.html
- assets/custom-css/pages/components/_header.scss
- collections/_components/badge.html
- collections/_components/toast.html
Added Badge and Toast pages content
- [ X ] This change requires a documentation update
NA
> Adding of Badge and Toast Pages

- _includes/page-component/component-code-snippet.html
- assets/custom-css/pages/components/_page.scss
- collections/_components/README.md
Added description feature for variant example section
**compDescTop** (optional): 
Description below the variant name. 
Can be use with either quotation marks "description here" or {% capture captureName %} for rich text.
**compDescBottom** (optional): 
Description below the variant example. 
Can be use with either quotation marks "description here" or {% capture captureName %} for rich text.
> page(component): add description feature for variant example

- collections/_components/input-group.html
> Write input group page

- collections/_components/progress-bar.html
> Progress bar

- collections/_patterns/error-summary.html
> Error Summary Pattern

- collections/_patterns/name.html
> Name Pattern

- collections/_patterns/phone-number.html
> Phone Number Pattern

- sgds/sass/sgds-theme/_sgds-variables.scss
- sgds/sass/sgds-theme/components/_alert.scss
> fix(alert): generate alert colors, add variables for theme-colors-set

- collections/_patterns/address.html
- collections/_patterns/date.html
> Date Pattern

- collections/_patterns/payment.html
> Payment Pattern

- _config.yml
- _includes/page-component/component-header.html
- collections/_patterns/email-address.html
- collections/_patterns/email.html
> Email Pattern

- collections/_components/masthead.html
> page(masthead)

- assets/uncompressed_images/component/progress-bar/anatomy-progressbar.svg
- collections/_components/progress-bar.html
Added content and image
Added content and image to progress bar page
> page (progress bar)

- collections/_components/table.html
Added content for usage and usability
Added in content for usage and usability. Have removed anatomy and spacing as the variations for these 2 are quite big.
Will add the content for those 2 sections in a future PR
> page (table)

- .github/workflows/publish-alpha.yml
- README.md
- package-lock.json
- package.json
Setup ghactions for dev branch --> alpha tag release . 
Update readme for instructions in publication 
rename package to @govtechsg/sgds
> Gh action 2.0.0 dev

- collections/_components/card.html
- sgds/sass/sgds-theme/components/_card.scss
Fix misalignment of input and subtitle of action cards
Change up the html structure of action-cards. 
update html
- [X ] Bug fix (non-breaking change which fixes an issue)
> fix(selectable cards): change html structure and update scss

- _config.yml
- _includes/page-component/component-header.html
- _layouts/layout-sidenav.html
- collections/_components/button.html
- collections/_components/date-picker.html
- collections/_components/dropdown.html
- collections/_components/masthead.html
- collections/_components/pagination.html
- collections/_components/quantity-toggle.html
- collections/_components/tooltip.html
- collections/_components/typeahead.html
- collections/_patterns/address.html
- collections/_patterns/date.html
- collections/_patterns/email-address.html
- collections/_patterns/error-summary.html
- collections/_patterns/name.html
- collections/_patterns/payment.html
- collections/_patterns/phone-number.html
> page(tooltip)

- _layouts/layout-sidenav.html
- assets/custom-css/layout/_grid.scss
> fixes(*): mobile layouts

- collections/_components/date-picker.html
- collections/_components/dropdown.html
> page(dropdown)

- package.json
This fix, resolves the following error when using @govtechsg/sgds package 
> fix(packaging): add sgds.css.map into dist files

- _includes/breadcrumb.html
> fix(breadcrumb): add current page title

- collections/_patterns/address.html
- collections/_patterns/date.html
- collections/_patterns/email-address.html
- collections/_patterns/name.html
- collections/_patterns/payment.html
- collections/_patterns/phone-number.html
Change autocomplete attributes to follow reacts, added naming guidelines as well. Tested in purple-hats and no error showed.
> fix(autocomplete)

- assets/custom-css/utilities/_sgds-example.scss
added overflow container for long images 
> style(img-preview): add overflows

- _data/navigation.yml
- contents/updates/content-updates.html
> added updates page content

- content/components/overview.html
- content/home.html
- content/patterns/overview.html
- content/templates/overview.html
Updated content for landing page, component overview, patterns overview and template overview.
> content update [landing, component, patterns and templates overview]

- .editorconfig
- _config.yml
- _includes/page-component/component-header.html
- assets/custom-css/base/_typography.scss
- assets/custom-css/utilities/_highlight.scss
- collections/_get-started/installation.html
> Update installation page 📖

- collections/_components/main-navigation.html
- package-lock.json
> (main navigation) megamenu, collapsed nav, sticky nav

- collections/_components/main-navigation.html
Changed ul to ol under usage guidelines
> content update (main nav)

- collections/_patterns/date.html
- collections/_patterns/email-address.html
- collections/_patterns/error-summary.html
- collections/_patterns/name.html
- collections/_patterns/phone-number.html
Removed extra spacing from usage and usability guidelines
Removed extra <li> under usage guidelines for date pattern
> patterns content update

- _includes/page-overview.html
- content/get-started/overview.html
1. add `img='noImg'` parameter to `{% include page-overview.html img='noImg' %}`
> chore(*): add hide show img for overview pages

- _config.yml
- _includes/footer.html
- assets/custom-css/layout/_grid.scss
- assets/custom-css/pages/_about.scss
- assets/custom-css/pages/_all.scss
- assets/custom-css/pages/faqs/page.scss
- content/home.html
- content/privacy-statement.html
- content/terms-of-use.html
Update content for:
1. Footer
2. Privacy Statement
3. Terms of Use
> Footer content

- _config.yml
- _includes/off-canvas-menu.html
Miss out the npm link in off-canvas mode 
> docs(npm): add npm link in off-canvas

- .github/workflows/publish-latest.yml
- .github/workflows/publish-pr.yml
Modify alpha to pre-release yml : rename publish-alpha.yml to publish-pr.yml
github action detects the right tag to publish correct to npm via alpha / beta tag 
- [ x] Code enhancement and update (non-breaking change)
> ci(ghaction): change alpha to pre-release setup

- .github/workflows/publish-latest.yml
> ci(publish): setup publish ci for v1

- assets/custom-css/utilities/_sgds-example.scss
- collections/_components/card.html
- [X ] Bug fix (non-breaking change which fixes an issue)
> fix(card): added mobile responsiveness for card variants

- _includes/head.html
- assets/custom-css/components/_navbar.scss
changes to cdn wil be retreive via latest tag. 
Preview masthead link color here https://v2dev.designsystem.gov.sg/
> fix(masthead): update cdn link to fetch latest

- sass/_root.scss
- sass/_section.scss
- sass/sgds.scss
> feat(section): add section helper classes

- _includes/head.html
Added meta's description and open graphs to `head`
> Sgds 402 meta desc

- CHANGELOG.md
- package-lock.json
- package.json
- sass/_functions.scss
> fix(function.scss): fix deprecated sass 1.56.0

- collections/_components/button.html
> docs(button): resolved #425 Incorrect button sizes in documentation

- _includes/page-component/component-code-snippet.html
- _includes/page-component/component-example.html
- collections/_components/combo-box.html
Create tabs for examples to display code from different frameworks
> [Experiment] Create tabs for examples to display code from different frameworks
